/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myjavaapp;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Lenovo
 */
public class MyBusiness extends javax.swing.JFrame {
    
    String[] question = {
    "Q.1 Name of the 1st deputy Prime Minister of India?",
     "Q.2 Which one is the Smallest Ocean in the World?",
     "Q.3 Dead Sea is locked between which two countries?",
     "Q.4 Which State has renamed the dragon fruit as 'Kamalam'?",
     "Q.5 Total Number of oceans in the world is______",
    };
    
    String[][] options = {
        {"Sardar Patel","R.N. Shukla","V.R. Gill","D.B. Mahawar","Sardar Vallabh Bhai Patel"},
        {"Indian","Pacafic","Atlantic","Arctic","Arctic"},
        {"Jordan & Sudan","Jordan & Israel","Turkey & UAE","UAE & Egypt","Jordan & Israel"},
        {"Assam","Gujarat","Tripura","Goa","Gujarat"},
        {"3","5","7","12","5"},
    };
    
     int index = 0, correct = 0;
     
     ButtonGroup bg = new ButtonGroup();

    /**
     * Creates new form MyGKPage
     */
    public MyBusiness() {
        
        initComponents();
        
        bg.add(jRadioButton_op1);
        bg.add(jRadioButton_op2);
        bg.add(jRadioButton_op3);
        bg.add(jRadioButton_op4);
        
        jButton_NextActionPerformed(null);
        
    }
    
 /*   public void getAnswer(JRadioButton rbutton)
    {
        String selected = rbutton.getText();
        String correct1 = options[index][4];
        if(selected.equals(correct1)){
            correct++;
        }
        index++;
         //System.out.println(rbtn.getText());
        //System.out.println(options[index][4]);
        jLabel_correctAns.setText("Answer : " + correct1);
    }
    */
    public void getSelectedOption(JRadioButton rbtn)
    {
        //"You Selected : " + rbtn.getText() + 
        jLabel_correctAns.setText(" Answer : " + options[index][4]);
        //jLabel_correctAns.setText(options[index][4]);
        if(rbtn.getText().equals(options[index][4]))
        {
                correct++;
        }
        
        index++;
        enableRbuttons(false);
    }
    
    public void enableRbuttons(boolean yes_or_no)
    {
        jRadioButton_op1.setEnabled(yes_or_no);
        jRadioButton_op2.setEnabled(yes_or_no);
        jRadioButton_op3.setEnabled(yes_or_no);
        jRadioButton_op4.setEnabled(yes_or_no);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_correctAns = new javax.swing.JLabel();
        jButton_Next = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JButton();
        jButton_CheckAns = new javax.swing.JButton();
        jPanel_Question = new javax.swing.JPanel();
        jLabel_Que = new javax.swing.JLabel();
        jRadioButton_op1 = new javax.swing.JRadioButton();
        jRadioButton_op2 = new javax.swing.JRadioButton();
        jRadioButton_op4 = new javax.swing.JRadioButton();
        jRadioButton_op3 = new javax.swing.JRadioButton();

        jLabel15.setBackground(new java.awt.Color(153, 153, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myjavaapp/BackArrow.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(153, 153, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myjavaapp/Home.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(102, 102, 255));
        jLabel8.setFont(new java.awt.Font("Cambria", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BUSINESS QUIZ");

        jLabel17.setBackground(new java.awt.Color(153, 153, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myjavaapp/Home.png"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(153, 153, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myjavaapp/BackArrow.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_correctAns.setFont(new java.awt.Font("Cambria", 1, 28)); // NOI18N
        jLabel_correctAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_correctAns.setText("Correct Answer : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_correctAns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_correctAns, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_Next.setBackground(new java.awt.Color(51, 51, 255));
        jButton_Next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Next.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButtonQuit.setBackground(new java.awt.Color(51, 51, 255));
        jButtonQuit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonQuit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuit.setText("Quit");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        jButton_CheckAns.setBackground(new java.awt.Color(51, 51, 255));
        jButton_CheckAns.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_CheckAns.setForeground(new java.awt.Color(255, 255, 255));
        jButton_CheckAns.setText("Check Answer");
        jButton_CheckAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CheckAnsActionPerformed(evt);
            }
        });

        jPanel_Question.setBackground(new java.awt.Color(204, 204, 204));

        jLabel_Que.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Que.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Que.setText("jLabel1");

        javax.swing.GroupLayout jPanel_QuestionLayout = new javax.swing.GroupLayout(jPanel_Question);
        jPanel_Question.setLayout(jPanel_QuestionLayout);
        jPanel_QuestionLayout.setHorizontalGroup(
            jPanel_QuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Que, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_QuestionLayout.setVerticalGroup(
            jPanel_QuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Que, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jRadioButton_op1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton_op1.setText("jRadioButton1");
        jRadioButton_op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_op1ActionPerformed(evt);
            }
        });

        jRadioButton_op2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton_op2.setText("jRadioButton2");
        jRadioButton_op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_op2ActionPerformed(evt);
            }
        });

        jRadioButton_op4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton_op4.setText("jRadioButton4");
        jRadioButton_op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_op4ActionPerformed(evt);
            }
        });

        jRadioButton_op3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jRadioButton_op3.setText("jRadioButton3");
        jRadioButton_op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_op3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonQuit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CheckAns)
                .addGap(18, 18, 18)
                .addComponent(jButton_Next)
                .addGap(24, 24, 24))
            .addComponent(jPanel_Question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_op3)
                        .addGap(101, 101, 101)
                        .addComponent(jRadioButton_op4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_op1)
                        .addGap(101, 101, 101)
                        .addComponent(jRadioButton_op2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_op1)
                    .addComponent(jRadioButton_op2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_op3)
                    .addComponent(jRadioButton_op4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CheckAns)
                    .addComponent(jButton_Next)
                    .addComponent(jButtonQuit))
                .addGap(53, 53, 53)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new MyHomePage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        new MyHomePage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        new MyCategoryPage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        new MyHomePage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
       
        if(jButton_Next.getText().equals("Restart Quiz"))
        {
                jButton_Next.setText("Next");
                jPanel_Question.setBackground(new java.awt.Color(204, 204, 204));
                index = 0;
                correct = 0;
        }
        
        if(index==question.length)
        {
                jLabel_Que.setText("Your Score: " + correct + "/" + question.length);
                if(correct > (float)question.length/2)
                {
                    jPanel_Question.setBackground(Color.GREEN);
                }
                else
                {
                    jPanel_Question.setBackground(Color.RED);
                }
                jButton_Next.setText("Restart Quiz");
        }
        
     /*   if(index<question.length)
        {
           
        }
     */
        else
        {
                 enableRbuttons(true);
        
                jLabel_Que.setText(question[index]);
                jRadioButton_op1.setText(options[index][0]);
                jRadioButton_op2.setText(options[index][1]);
                jRadioButton_op3.setText(options[index][2]);
                jRadioButton_op4.setText(options[index][3]);


                if(index==question.length-1)
                {
                    jButton_Next.setText("Result");
                }
                 
        }
        bg.clearSelection();
        
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
            new MyHomePage().setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jButton_CheckAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CheckAnsActionPerformed

        
       //     jLabel_correctAns.setText(" Answer : " + options[index][4]);
//        getSelectedOption(jRadioButton_op1);
          //String selected = rbutton.getText();
      //  String correct = options[index][4];
         //System.out.println(rbtn.getText());
        //System.out.println(options[index][4]);
    //      String correct = options[index][4];
       //jLabel_correctAns.setText("Answer : " + correct);
     //   getAnswer(correct[index][4]);
       //  System.out.println(rbtn.getText());
        //System.out.println(options[index][4]);
        
     //   String s1 = rbtn.get
        //String s = System.out.println(rbtn.get)
        //jLabel_correctAns.setText("Answer : " + rbtn.getText());
    }//GEN-LAST:event_jButton_CheckAnsActionPerformed

    private void jRadioButton_op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_op3ActionPerformed
            getSelectedOption(jRadioButton_op3);
    }//GEN-LAST:event_jRadioButton_op3ActionPerformed

    private void jRadioButton_op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_op1ActionPerformed
            getSelectedOption(jRadioButton_op1);
    }//GEN-LAST:event_jRadioButton_op1ActionPerformed

    private void jRadioButton_op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_op2ActionPerformed
            getSelectedOption(jRadioButton_op2);
    }//GEN-LAST:event_jRadioButton_op2ActionPerformed

    private void jRadioButton_op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_op4ActionPerformed
            getSelectedOption(jRadioButton_op4);
    }//GEN-LAST:event_jRadioButton_op4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBusiness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButton_CheckAns;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Que;
    private javax.swing.JLabel jLabel_correctAns;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Question;
    private javax.swing.JRadioButton jRadioButton_op1;
    private javax.swing.JRadioButton jRadioButton_op2;
    private javax.swing.JRadioButton jRadioButton_op3;
    private javax.swing.JRadioButton jRadioButton_op4;
    // End of variables declaration//GEN-END:variables
}
